// Generated by fsm from the state machine "shop". Do not edit.
#pragma once

// The guards and actions the state machine "shop" calls.
// Implement them and pass the implementation to ShopFsm's constructor.
class ShopFsmActions {
public:
    virtual ~ShopFsmActions() = default;

    // Guards
    virtual bool large() const = 0;
    virtual bool paidInFull() const = 0;
    virtual bool regular() const = 0;

    // Actions
    virtual void close() = 0;
    virtual void computeTotal() = 0;
    virtual void openChat() = 0;
    virtual void receipt() = 0;
};
