// Generated by fsm from the state machine "shop". Do not edit.
#include "ShopFsm.h"

#include <boost/sml.hpp>

namespace {

namespace sml = boost::sml;

namespace event {
struct buy {};
struct quickBuy {};
struct fraud {};
struct help {};
struct emergency {};
struct next {};
struct approved {};
struct cash {};
struct card {};
struct abort {};
struct packed {};
struct sent {};
struct reopen {};
struct back {};
struct refund {};
}  // namespace event

// The composite state "review".
struct review {
    auto operator()() const {
        using namespace sml::literals;
        const auto regular = [](const ShopFsmActions& actions) { return actions.regular(); };
        return sml::make_transition_table(
            (*"depth"_s) [regular] = "quick"_s,
            "depth"_s = "thorough"_s
        );
    }
};

// The composite state "checkout".
struct checkout {
    auto operator()() const {
        using namespace sml::literals;
        const auto large = [](const ShopFsmActions& actions) { return actions.large(); };
        const auto computeTotal = [](ShopFsmActions& actions) { actions.computeTotal(); };
        return sml::make_transition_table(
            // checkout.H:
            // Back to the step the customer left.
            "address"_s(sml::H) + sml::event<event::next> / computeTotal = "route"_s,
            "route"_s [large] = sml::state<review>,
            "route"_s = "paying"_s,
            sml::state<review> + sml::event<event::approved> = "paying"_s,
            "paying"_s + sml::event<event::cash> = "paid"_s,
            "paying"_s + sml::event<event::card> = "paid"_s,
            "paid"_s = sml::X
        );
    }
};

// The orthogonal state "shipping".
struct shipping {
    auto operator()() const {
        using namespace sml::literals;
        const auto paidInFull = [](const ShopFsmActions& actions) { return actions.paidInFull(); };
        return sml::make_transition_table(
            *"packing"_s + sml::event<event::packed> = "packed"_s,
            "packed"_s = sml::X,
            *"invoicing"_s + sml::event<event::sent> = "sent"_s,
            "sent"_s [paidInFull] = sml::X
        );
    }
};

struct machine {
    auto operator()() const {
        using namespace sml::literals;
        const auto openChat = [](ShopFsmActions& actions) { actions.openChat(); };
        const auto receipt = [](ShopFsmActions& actions) { actions.receipt(); };
        const auto close = [](ShopFsmActions& actions) { actions.close(); };
        return sml::make_transition_table(
            *"browsing"_s + sml::event<event::buy> = sml::state<checkout>,
            "browsing"_s + sml::event<event::quickBuy> = sml::state<checkout>,
            "browsing"_s + sml::event<event::fraud> = sml::X,
            "browsing"_s + sml::event<event::help> = "support"_s,
            "browsing"_s + sml::event<event::emergency> = "support"_s,
            "support"_s + sml::on_entry<sml::_> / openChat,
            "support"_s = "browsing"_s,
            // checkout:
            // «secure»
            sml::state<checkout> / receipt = sml::state<shipping>,
            sml::state<shipping> / close = "done"_s,
            "done"_s + sml::event<event::reopen> = sml::state<checkout>,
            "done"_s + sml::event<event::back> = sml::state<checkout>,
            "done"_s + sml::event<event::refund> = sml::X,
            "done"_s = sml::X
            // refunded:
            // Money returned.
            // terminate:
            // Fraud closes the shop.
        );
    }
};

}  // namespace

struct ShopFsm::Machine {
    explicit Machine(ShopFsmActions& actions) : sm{actions} {}
    sml::sm<machine> sm;
};

ShopFsm::ShopFsm(ShopFsmActions& actions) : machine_{std::make_unique<Machine>(actions)} {}

ShopFsm::~ShopFsm() = default;

void ShopFsm::buy() { machine_->sm.process_event(event::buy{}); }
void ShopFsm::quickBuy() { machine_->sm.process_event(event::quickBuy{}); }
void ShopFsm::fraud() { machine_->sm.process_event(event::fraud{}); }
void ShopFsm::help() { machine_->sm.process_event(event::help{}); }
void ShopFsm::emergency() { machine_->sm.process_event(event::emergency{}); }
void ShopFsm::next() { machine_->sm.process_event(event::next{}); }
void ShopFsm::approved() { machine_->sm.process_event(event::approved{}); }
void ShopFsm::cash() { machine_->sm.process_event(event::cash{}); }
void ShopFsm::card() { machine_->sm.process_event(event::card{}); }
void ShopFsm::abort() { machine_->sm.process_event(event::abort{}); }
void ShopFsm::packed() { machine_->sm.process_event(event::packed{}); }
void ShopFsm::sent() { machine_->sm.process_event(event::sent{}); }
void ShopFsm::reopen() { machine_->sm.process_event(event::reopen{}); }
void ShopFsm::back() { machine_->sm.process_event(event::back{}); }
void ShopFsm::refund() { machine_->sm.process_event(event::refund{}); }
