// Generated by fsm from the state machine "shop". Do not edit.
#include "ShopFsm.h"
#include "SupportFsm.h"

#include <boost/sml.hpp>
#include <deque>
#include <functional>
#include <utility>

namespace {

namespace sml = boost::sml;

namespace event {
struct buy {};
struct quickBuy {};
struct fraud {};
struct help {};
struct emergency {};
struct next {};
struct approved {};
struct cash {};
struct card {};
struct abort {};
struct packed {};
struct sent {};
struct reopen {};
struct back {};
struct refund {};
struct complain {};
}  // namespace event

// The events the machine sends itself, and the state it waits in until entered.
namespace internal {
struct stopped {};
struct enter {};
struct stop {};
struct enter_reorder {};
struct terminated {};
struct helpdesk_finished {};
struct helpdesk_exit_escalated {};
struct aftersales_finished {};
}  // namespace internal

// Whether the machine reached a terminate state, its own or one of a machine it
// runs: it ends once the current event is done.
struct status {
    bool terminated = false;
};

// The machines the submachine states run, and the entry point each starts at next.
struct submachines {
    SupportFsm& helpdesk;
    SupportFsm::Entry helpdesk_entry = SupportFsm::Entry::initial;
    SupportFsm& aftersales;
    SupportFsm::Entry aftersales_entry = SupportFsm::Entry::initial;
};

// The composite state "review".
struct review {
    auto operator()() const {
        using namespace sml::literals;
        const auto regular = [](const ShopFsmActions& actions) { return actions.regular(); };
        return sml::make_transition_table(
            (*"depth"_s) [regular] = "quick"_s,
            "depth"_s = "thorough"_s
        );
    }
};

// The composite state "checkout".
struct checkout {
    auto operator()() const {
        using namespace sml::literals;
        const auto large = [](const ShopFsmActions& actions) { return actions.large(); };
        const auto computeTotal = [](ShopFsmActions& actions) { actions.computeTotal(); };
        return sml::make_transition_table(
            // checkout.H:
            // Back to the step the customer left.
            "address"_s(sml::H) + sml::event<event::next> / computeTotal = "route"_s,
            "route"_s [large] = sml::state<review>,
            "route"_s = "paying"_s,
            sml::state<review> + sml::event<event::approved> = "paying"_s,
            "paying"_s + sml::event<event::cash> = "paid"_s,
            "paying"_s + sml::event<event::card> = "paid"_s,
            "paid"_s = sml::X
        );
    }
};

// The orthogonal state "shipping".
struct shipping {
    auto operator()() const {
        using namespace sml::literals;
        const auto paidInFull = [](const ShopFsmActions& actions) { return actions.paidInFull(); };
        return sml::make_transition_table(
            *"packing"_s + sml::event<event::packed> = "packed"_s,
            "packed"_s = sml::X,
            *"invoicing"_s + sml::event<event::sent> = "sent"_s,
            "sent"_s [paidInFull] = sml::X
        );
    }
};

struct machine {
    auto operator()() const {
        using namespace sml::literals;
        using sml::operator!, sml::operator&&, sml::operator||, sml::operator,;
        const auto loadBasket = [](ShopFsmActions& actions) { actions.loadBasket(); };
        const auto openChat = [](ShopFsmActions& actions) { actions.openChat(); };
        const auto page = [](ShopFsmActions& actions) { actions.page(); };
        const auto receipt = [](ShopFsmActions& actions) { actions.receipt(); };
        const auto close = [](ShopFsmActions& actions) { actions.close(); };
        return sml::make_transition_table(
            *sml::state<::internal::stopped> + sml::event<::internal::enter> = "browsing"_s,
            sml::state<::internal::stopped> + sml::event<::internal::enter_reorder> / loadBasket = sml::state<checkout>,
            "browsing"_s + sml::event<event::buy> = sml::state<checkout>,
            "browsing"_s + sml::event<event::quickBuy> = sml::state<checkout>,
            "browsing"_s + sml::event<event::fraud> = sml::state<::internal::terminated>,
            "browsing"_s + sml::event<event::help> = "helpdesk"_s,
            "browsing"_s + sml::event<event::emergency> / [](::submachines& s) { s.helpdesk_entry = SupportFsm::Entry::urgent; } = "helpdesk"_s,
            "helpdesk"_s + sml::on_entry<sml::_> / (openChat, [](::submachines& s) { s.helpdesk.enterFsm(std::exchange(s.helpdesk_entry, SupportFsm::Entry::initial)); }),
            "helpdesk"_s + sml::on_exit<sml::_> / [](::submachines& s) { s.helpdesk.stopFsm(); },
            "helpdesk"_s + sml::event<::internal::helpdesk_finished> = "browsing"_s,
            "helpdesk"_s + sml::event<::internal::helpdesk_exit_escalated> / page = sml::state<checkout>,
            // checkout:
            // «secure»
            sml::state<checkout> / receipt = sml::state<shipping>,
            sml::state<shipping> / close = "done"_s,
            "done"_s + sml::event<event::reopen> = sml::state<checkout>,
            "done"_s + sml::event<event::back> = sml::state<checkout>,
            "done"_s + sml::event<event::refund> = sml::X,
            "done"_s + sml::event<event::complain> = "aftersales"_s,
            "done"_s = sml::X,
            "aftersales"_s + sml::on_entry<sml::_> / [](::submachines& s) { s.aftersales.enterFsm(std::exchange(s.aftersales_entry, SupportFsm::Entry::initial)); },
            "aftersales"_s + sml::on_exit<sml::_> / [](::submachines& s) { s.aftersales.stopFsm(); },
            "aftersales"_s + sml::event<::internal::aftersales_finished> = "done"_s,
            // refunded:
            // Money returned.
            // terminate:
            // Fraud closes the shop.
            sml::state<::internal::terminated> + sml::on_entry<sml::_> / [](::status& s) { s.terminated = true; },
            "browsing"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            "helpdesk"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            sml::state<checkout> + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            sml::state<shipping> + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            "done"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            "aftersales"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>
        );
    }
};

}  // namespace

struct ShopFsm::Machine {
    // Hands what the machine of "helpdesk" reports to this one.
    struct HelpdeskListener : SupportFsmListener {
        explicit HelpdeskListener(ShopFsm& fsm) : fsm{fsm} {}
        void onTerminated() override {
            fsm.machine_->status.terminated = true;
            if (!fsm.machine_->busy) {
                fsm.report();
            }
        }
        void onFinished() override {
            if (fsm.machine_->process(internal::helpdesk_finished{})) {
                fsm.report();
            }
        }
        void onExitEscalated() override {
            if (fsm.machine_->process(internal::helpdesk_exit_escalated{})) {
                fsm.report();
            }
        }
        ShopFsm& fsm;
    };

    // Hands what the machine of "aftersales" reports to this one.
    struct AftersalesListener : SupportFsmListener {
        explicit AftersalesListener(ShopFsm& fsm) : fsm{fsm} {}
        void onTerminated() override {
            fsm.machine_->status.terminated = true;
            if (!fsm.machine_->busy) {
                fsm.report();
            }
        }
        void onFinished() override {
            if (fsm.machine_->process(internal::aftersales_finished{})) {
                fsm.report();
            }
        }
        ShopFsm& fsm;
    };

    Machine(ShopFsm& fsm, ShopFsmActions& actions, SupportFsm& helpdesk, SupportFsm& aftersales)
        : machines{.helpdesk = helpdesk, .aftersales = aftersales},
          helpdesk_listener{fsm},
          aftersales_listener{fsm},
          sm{actions, machines, status} {
        helpdesk.terminateFsm();
        helpdesk.setListener(&helpdesk_listener);
        aftersales.terminateFsm();
        aftersales.setListener(&aftersales_listener);
    }

    ~Machine() {
        machines.helpdesk.setListener(nullptr);
        machines.aftersales.setListener(nullptr);
    }

    // Processes an event, or queues it while processing another, since a
    // submachine may report while this machine enters it. Returns whether it
    // processed the event.
    template <class Event>
    bool process(const Event& event) {
        if (busy) {
            queue.push_back([this, event] { sm.process_event(event); });
            return false;
        }
        busy = true;
        sm.process_event(event);
        while (!queue.empty() && !status.terminated) {
            auto next = std::move(queue.front());
            queue.pop_front();
            next();
        }
        busy = false;
        return true;
    }

    ::submachines machines;
    HelpdeskListener helpdesk_listener;
    AftersalesListener aftersales_listener;
    ::status status;
    sml::sm<machine> sm;
    bool busy = false;
    std::deque<std::function<void()>> queue;
};

ShopFsm::ShopFsm(ShopFsmActions& actions, SupportFsm& helpdesk, SupportFsm& aftersales)
    : actions_{actions},
      helpdesk_{helpdesk},
      aftersales_{aftersales},
      machine_{std::make_unique<Machine>(*this, actions, helpdesk, aftersales)} {}

ShopFsm::~ShopFsm() = default;

void ShopFsm::enterFsm(Entry entry) {
    stopFsm();
    switch (entry) {
    case Entry::initial:
        if (machine_->process(internal::enter{})) {
            report();
        }
        break;
    case Entry::reorder:
        if (machine_->process(internal::enter_reorder{})) {
            report();
        }
        break;
    }
}

void ShopFsm::stopFsm() {
    machine_->sm.process_event(internal::stop{});
    terminateFsm();
}

void ShopFsm::terminateFsm() {
    machine_.reset();
    machine_ = std::make_unique<Machine>(*this, actions_, helpdesk_, aftersales_);
}

void ShopFsm::setListener(ShopFsmListener* listener) {
    listener_ = listener;
}

void ShopFsm::report() {
    if (machine_->status.terminated) {
        terminateFsm();
        if (listener_ != nullptr) {
            listener_->onTerminated();
        }
        return;
    }
    if (listener_ == nullptr) {
        return;
    }
    if (machine_->sm.is(sml::X)) {
        stopFsm();
        listener_->onFinished();
    }
}

void ShopFsm::buy() {
    if (machine_->process(event::buy{})) {
        report();
    }
}

void ShopFsm::quickBuy() {
    if (machine_->process(event::quickBuy{})) {
        report();
    }
}

void ShopFsm::fraud() {
    if (machine_->process(event::fraud{})) {
        report();
    }
}

void ShopFsm::help() {
    if (machine_->process(event::help{})) {
        report();
    }
}

void ShopFsm::emergency() {
    if (machine_->process(event::emergency{})) {
        report();
    }
}

void ShopFsm::next() {
    if (machine_->process(event::next{})) {
        report();
    }
}

void ShopFsm::approved() {
    if (machine_->process(event::approved{})) {
        report();
    }
}

void ShopFsm::cash() {
    if (machine_->process(event::cash{})) {
        report();
    }
}

void ShopFsm::card() {
    if (machine_->process(event::card{})) {
        report();
    }
}

void ShopFsm::abort() {
    if (machine_->process(event::abort{})) {
        report();
    }
}

void ShopFsm::packed() {
    if (machine_->process(event::packed{})) {
        report();
    }
}

void ShopFsm::sent() {
    if (machine_->process(event::sent{})) {
        report();
    }
}

void ShopFsm::reopen() {
    if (machine_->process(event::reopen{})) {
        report();
    }
}

void ShopFsm::back() {
    if (machine_->process(event::back{})) {
        report();
    }
}

void ShopFsm::refund() {
    if (machine_->process(event::refund{})) {
        report();
    }
}

void ShopFsm::complain() {
    if (machine_->process(event::complain{})) {
        report();
    }
}
