// Generated by fsm from the state machine "shop". Do not edit.
#pragma once

// The events the state machine "shop" reacts to.
class ShopFsmEvents {
public:
    virtual ~ShopFsmEvents() = default;

    virtual void buy() = 0;
    virtual void quickBuy() = 0;
    virtual void fraud() = 0;
    virtual void help() = 0;
    virtual void emergency() = 0;
    virtual void next() = 0;
    virtual void approved() = 0;
    virtual void cash() = 0;
    virtual void card() = 0;
    virtual void abort() = 0;
    virtual void packed() = 0;
    virtual void sent() = 0;
    virtual void reopen() = 0;
    virtual void back() = 0;
    virtual void refund() = 0;
};
