// Generated by fsm from the state machine "shop". Do not edit.
#pragma once

#include "ShopFsmActions.h"
#include "ShopFsmEvents.h"

#include <memory>

// The state machine "shop".
class ShopFsm : public ShopFsmEvents {
public:
    explicit ShopFsm(ShopFsmActions& actions);
    ~ShopFsm() override;

    ShopFsm(const ShopFsm&) = delete;
    ShopFsm& operator=(const ShopFsm&) = delete;

    void buy() override;
    void quickBuy() override;
    void fraud() override;
    void help() override;
    void emergency() override;
    void next() override;
    void approved() override;
    void cash() override;
    void card() override;
    void abort() override;
    void packed() override;
    void sent() override;
    void reopen() override;
    void back() override;
    void refund() override;

private:
    struct Machine;
    std::unique_ptr<Machine> machine_;
};
