<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>fsm</string>
	<key>scopeName</key>
	<string>source.fsm</string>
	<key>fileTypes</key>
	<array>
		<string>fsm</string>
	</array>
	<key>uuid</key>
	<string>6F1D3C1E-4B8A-4E43-9C55-2A7E0D6B1F02</string>
	<key>patterns</key>
	<array>
		<dict><key>include</key><string>#comment</string></dict>
		<dict><key>include</key><string>#note</string></dict>
		<dict><key>include</key><string>#machine</string></dict>
		<dict><key>include</key><string>#initial</string></dict>
		<dict><key>include</key><string>#parallel</string></dict>
		<dict><key>include</key><string>#point</string></dict>
		<dict><key>include</key><string>#history</string></dict>
		<dict><key>include</key><string>#ending</string></dict>
		<dict><key>include</key><string>#declaration</string></dict>
		<dict><key>include</key><string>#stereotype</string></dict>
		<dict><key>include</key><string>#behaviour</string></dict>
		<dict><key>include</key><string>#trigger</string></dict>
		<dict><key>include</key><string>#after</string></dict>
		<dict><key>include</key><string>#guard</string></dict>
		<dict><key>include</key><string>#defer</string></dict>
		<dict><key>include</key><string>#actions</string></dict>
		<dict><key>include</key><string>#goto</string></dict>
		<dict><key>include</key><string>#braces</string></dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>(#).*$</string>
			<key>name</key>
			<string>comment.line.number-sign.fsm</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>punctuation.definition.comment.fsm</string></dict>
			</dict>
		</dict>
		<key>machine</key>
		<dict>
			<key>match</key>
			<string>\b(fsm)\s+([A-Za-z_]\w*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>storage.type.machine.fsm</string></dict>
				<key>2</key>
				<dict><key>name</key><string>entity.name.type.machine.fsm</string></dict>
			</dict>
		</dict>
		<key>initial</key>
		<dict>
			<key>match</key>
			<string>\binitial\b</string>
			<key>name</key>
			<string>storage.modifier.initial.fsm</string>
		</dict>
		<key>parallel</key>
		<dict>
			<key>match</key>
			<string>\b(parallel)\s+(state)\s+([A-Za-z_]\w*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>storage.modifier.parallel.fsm</string></dict>
				<key>2</key>
				<dict><key>name</key><string>storage.type.state.fsm</string></dict>
				<key>3</key>
				<dict><key>name</key><string>entity.name.type.state.fsm</string></dict>
			</dict>
		</dict>
		<key>point</key>
		<dict>
			<key>match</key>
			<string>\b(entry|exit)\s+(point)\s+([A-Za-z_]\w*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>storage.type.pseudostate.fsm</string></dict>
				<key>2</key>
				<dict><key>name</key><string>storage.type.pseudostate.fsm</string></dict>
				<key>3</key>
				<dict><key>name</key><string>entity.name.type.state.fsm</string></dict>
			</dict>
		</dict>
		<key>history</key>
		<dict>
			<key>match</key>
			<string>(?&lt;![\w.])H\*?(?![\w*])</string>
			<key>name</key>
			<string>storage.type.pseudostate.fsm</string>
		</dict>
		<key>ending</key>
		<dict>
			<key>match</key>
			<string>\b(final|terminate)\s+(state)\b(?:\s+(?!(?:state|parallel|submachine|final|terminate|choice|junction|fork|join|entry|exit|do|on|after|invariant|initial|goto|H)\b)([A-Za-z_]\w*))?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>storage.type.state.fsm</string></dict>
				<key>2</key>
				<dict><key>name</key><string>storage.type.state.fsm</string></dict>
				<key>3</key>
				<dict><key>name</key><string>entity.name.type.state.fsm</string></dict>
			</dict>
		</dict>
		<key>declaration</key>
		<dict>
			<key>match</key>
			<string>\b(state|submachine|region|choice|junction|fork|join)\s+([A-Za-z_]\w*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>storage.type.state.fsm</string></dict>
				<key>2</key>
				<dict><key>name</key><string>entity.name.type.state.fsm</string></dict>
			</dict>
		</dict>
		<key>note</key>
		<dict>
			<key>begin</key>
			<string>\|</string>
			<key>end</key>
			<string>\|</string>
			<key>name</key>
			<string>comment.block.documentation.note.fsm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.fsm</string>
				</dict>
			</array>
		</dict>
		<key>stereotype</key>
		<dict>
			<key>match</key>
			<string>(&lt;&lt;)\s*([A-Za-z_]\w*)\s*(&gt;&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>punctuation.definition.stereotype.begin.fsm</string></dict>
				<key>2</key>
				<dict><key>name</key><string>storage.modifier.stereotype.fsm</string></dict>
				<key>3</key>
				<dict><key>name</key><string>punctuation.definition.stereotype.end.fsm</string></dict>
			</dict>
		</dict>
		<key>behaviour</key>
		<dict>
			<key>match</key>
			<string>\b(entry|exit|do|invariant)\b</string>
			<key>name</key>
			<string>keyword.other.behaviour.fsm</string>
		</dict>
		<key>trigger</key>
		<dict>
			<key>match</key>
			<string>\b(on)\s+([A-Za-z_]\w*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>keyword.control.trigger.fsm</string></dict>
				<key>2</key>
				<dict><key>name</key><string>variable.parameter.event.fsm</string></dict>
			</dict>
		</dict>
		<key>after</key>
		<dict>
			<key>match</key>
			<string>\b(after)\s*(\()\s*(?:(\d+(?:\.\d+)?)(ms|s)\b|([A-Za-z_]\w*))\s*(\))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>keyword.control.trigger.fsm</string></dict>
				<key>2</key>
				<dict><key>name</key><string>punctuation.section.parens.begin.fsm</string></dict>
				<key>3</key>
				<dict><key>name</key><string>constant.numeric.duration.fsm</string></dict>
				<key>4</key>
				<dict><key>name</key><string>keyword.other.unit.fsm</string></dict>
				<key>5</key>
				<dict><key>name</key><string>entity.name.function.delay.fsm</string></dict>
				<key>6</key>
				<dict><key>name</key><string>punctuation.section.parens.end.fsm</string></dict>
			</dict>
		</dict>
		<key>guard</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict><key>name</key><string>punctuation.section.brackets.begin.fsm</string></dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict><key>name</key><string>punctuation.section.brackets.end.fsm</string></dict>
			</dict>
			<key>contentName</key>
			<string>meta.guard.fsm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\belse\b</string>
					<key>name</key>
					<string>keyword.control.else.fsm</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(and|or|not)\b</string>
					<key>name</key>
					<string>keyword.operator.logical.fsm</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[()]</string>
					<key>name</key>
					<string>punctuation.section.parens.fsm</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Za-z_]\w*\b</string>
					<key>name</key>
					<string>entity.name.function.guard.fsm</string>
				</dict>
			</array>
		</dict>
		<key>defer</key>
		<dict>
			<key>match</key>
			<string>(/)\s*(defer)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>punctuation.separator.actions.fsm</string></dict>
				<key>2</key>
				<dict><key>name</key><string>keyword.other.defer.fsm</string></dict>
			</dict>
		</dict>
		<key>actions</key>
		<dict>
			<key>begin</key>
			<string>(/)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>punctuation.separator.actions.fsm</string></dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\w)(?!\s*,)</string>
			<key>patterns</key>
			<array>
				<dict><key>include</key><string>#comment</string></dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.comma.fsm</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Za-z_]\w*\b</string>
					<key>name</key>
					<string>entity.name.function.action.fsm</string>
				</dict>
			</array>
		</dict>
		<key>goto</key>
		<dict>
			<key>match</key>
			<string>\b(goto)\s+(?:(local)\s+)?(?:(final|terminate)\b|(?:([A-Za-z_]\w*)(\.))?(H\*?)(?![\w*])|([A-Za-z_]\w*))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict><key>name</key><string>keyword.control.goto.fsm</string></dict>
				<key>2</key>
				<dict><key>name</key><string>storage.modifier.local.fsm</string></dict>
				<key>3</key>
				<dict><key>name</key><string>keyword.other.target.fsm</string></dict>
				<key>4</key>
				<dict><key>name</key><string>entity.name.type.state.fsm</string></dict>
				<key>5</key>
				<dict><key>name</key><string>punctuation.accessor.fsm</string></dict>
				<key>6</key>
				<dict><key>name</key><string>keyword.other.history.fsm</string></dict>
				<key>7</key>
				<dict><key>name</key><string>entity.name.type.state.fsm</string></dict>
			</dict>
		</dict>
		<key>braces</key>
		<dict>
			<key>match</key>
			<string>[{}]</string>
			<key>name</key>
			<string>punctuation.section.block.fsm</string>
		</dict>
	</dict>
</dict>
</plist>
