// Generated by fsm. Do not edit.
#pragma once

#include <chrono>
#include <cstdint>
#include <functional>

// Starts and cancels the timers of the time triggers, such as after(90s), of
// the state machines fsm generates. Implement it once and pass it to every
// machine that has time triggers.
//
// A machine starts a timer when it enters the state waiting for it, and cancels
// it when it leaves that state. Call fire on the thread that sends the machine
// its events, and never from within startTimer or cancelTimer. A timer that
// fires after it was cancelled does nothing.
class FsmTimers {
public:
    using Id = std::uint64_t;

    virtual ~FsmTimers() = default;

    // Calls fire once, after delay, unless the timer is cancelled first.
    virtual Id startTimer(std::chrono::milliseconds delay, std::function<void()> fire) = 0;
    // Cancels a timer. A timer that has fired or was cancelled is ignored.
    virtual void cancelTimer(Id id) = 0;
};
