// Generated by fsm from the state machine "support". Do not edit.
#pragma once

// The guards and actions the state machine "support" calls.
// Implement them and pass the implementation to SupportFsm's constructor.
class SupportFsmActions {
public:
    virtual ~SupportFsmActions() = default;
};
