// Generated by fsm from the state machine "support". Do not edit.
#include "SupportFsm.h"

#include <boost/sml.hpp>

namespace {

namespace sml = boost::sml;

namespace event {
struct human {};
struct solved {};
struct escalate {};
}  // namespace event

// The events the machine sends itself, and the state it waits in until entered.
namespace internal {
struct stopped {};
struct enter {};
struct stop {};
struct enter_urgent {};
}  // namespace internal

struct machine {
    auto operator()() const {
        using namespace sml::literals;
        return sml::make_transition_table(
            *sml::state<::internal::stopped> + sml::event<::internal::enter> = "bot"_s,
            sml::state<::internal::stopped> + sml::event<::internal::enter_urgent> = "agent"_s,
            "bot"_s + sml::event<event::human> = "agent"_s,
            "bot"_s + sml::event<event::solved> = sml::X,
            "agent"_s + sml::event<event::solved> = sml::X,
            "agent"_s + sml::event<event::escalate> = "escalated"_s,
            "bot"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            "agent"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>
        );
    }
};

}  // namespace

struct SupportFsm::Machine {
    explicit Machine(SupportFsmActions& actions) : sm{actions} {}
    sml::sm<machine> sm;
};

SupportFsm::SupportFsm(SupportFsmActions& actions)
    : actions_{actions},
      machine_{std::make_unique<Machine>(actions)} {}

SupportFsm::~SupportFsm() = default;

void SupportFsm::enterFsm(Entry entry) {
    stopFsm();
    switch (entry) {
    case Entry::initial:
        machine_->sm.process_event(internal::enter{});
        report();
        break;
    case Entry::urgent:
        machine_->sm.process_event(internal::enter_urgent{});
        report();
        break;
    }
}

void SupportFsm::stopFsm() {
    machine_->sm.process_event(internal::stop{});
    machine_.reset();
    machine_ = std::make_unique<Machine>(actions_);
}

void SupportFsm::setListener(SupportFsmListener* listener) {
    listener_ = listener;
}

void SupportFsm::report() {
    using namespace sml::literals;
    if (listener_ == nullptr) {
        return;
    }
    if (machine_->sm.is(sml::X)) {
        stopFsm();
        listener_->onFinished();
    } else if (machine_->sm.is("escalated"_s)) {
        stopFsm();
        listener_->onExitEscalated();
    }
}

void SupportFsm::human() {
    machine_->sm.process_event(event::human{});
    report();
}

void SupportFsm::solved() {
    machine_->sm.process_event(event::solved{});
    report();
}

void SupportFsm::escalate() {
    machine_->sm.process_event(event::escalate{});
    report();
}
