// Generated by fsm from the state machine "support". Do not edit.
#pragma once

#include "SupportFsmActions.h"
#include "SupportFsmEvents.h"

#include <memory>

// What the state machine "support" tells when it ends, as a submachine does.
class SupportFsmListener {
public:
    virtual ~SupportFsmListener() = default;

    // It reached its final state.
    virtual void onFinished() {}
    // It reached a terminate state.
    virtual void onTerminated() {}
    // It left by its exit point "escalated".
    virtual void onExitEscalated() {}
};

// The state machine "support".
class SupportFsm : public SupportFsmEvents {
public:
    // Where enterFsm starts the machine: its initial state or an entry point.
    enum class Entry { initial, urgent };

    explicit SupportFsm(SupportFsmActions& actions);
    ~SupportFsm() override;

    SupportFsm(const SupportFsm&) = delete;
    SupportFsm& operator=(const SupportFsm&) = delete;

    // Starts the machine, again if it runs, in its initial state or at an entry point.
    void enterFsm(Entry entry = Entry::initial);
    // Stops the machine: it leaves its states, running their exit behaviours, and
    // ignores every event until entered again.
    void stopFsm();
    // Ends the machine at once, as a terminate state does: no exit behaviour runs,
    // and it ignores every event until entered again.
    void terminateFsm();
    // Tells listener when the machine ends; nullptr tells no one.
    void setListener(SupportFsmListener* listener);

    void human() override;
    void solved() override;
    void escalate() override;

private:
    void report();

    struct Machine;
    SupportFsmActions& actions_;
    SupportFsmListener* listener_ = nullptr;
    std::unique_ptr<Machine> machine_;
};
