// Generated by fsm from the state machine "support". Do not edit.
#pragma once

// The events the state machine "support" reacts to.
class SupportFsmEvents {
public:
    virtual ~SupportFsmEvents() = default;

    virtual void human() = 0;
    virtual void solved() = 0;
    virtual void escalate() = 0;
};
