// Generated by fsm from the state machine "uml". Do not edit.
#include "UmlFsm.h"
#include "ChildFsm.h"

#include <boost/sml.hpp>
#include <deque>
#include <functional>
#include <utility>

namespace {

namespace sml = boost::sml;

namespace event {
struct pause {};
struct resume {};
struct after_5s {};
struct after_retryDelay {};
struct split {};
struct abort {};
struct enter {};
struct l {};
struct r {};
struct back {};
struct leave {};
struct again {};
struct note {};
}  // namespace event

// The events the machine sends itself, and the state it waits in until entered.
namespace internal {
struct stopped {};
struct enter {};
struct stop {};
struct sub_finished {};
}  // namespace internal

// The machines the submachine states run, and the entry point each starts at next.
struct submachines {
    ChildFsm& sub;
    ChildFsm::Entry sub_entry = ChildFsm::Entry::initial;
};

// The orthogonal state "both".
struct both {
    auto operator()() const {
        using namespace sml::literals;
        return sml::make_transition_table(
            *"left"_s + sml::event<event::l> = sml::X,
            *"right"_s + sml::event<event::r> = sml::X
        );
    }
};

// The composite state "outer".
struct outer {
    auto operator()() const {
        using namespace sml::literals;
        return sml::make_transition_table(
            *"outer.initial"_s / [] {} = "inner"_s,
            "inner"_s + sml::event<event::again> = "inner"_s,
            // Not drawn.
            "inner"_s + sml::event<event::note> / [] {}
        );
    }
};

struct machine {
    auto operator()() const {
        using namespace sml::literals;
        return sml::make_transition_table(
            *sml::state<::internal::stopped> + sml::event<::internal::enter> = "check"_s,
            // "check"_s [retries > 3] = sml::X
            // "check"_s [retries <= 3] = "work"_s
            "merge"_s = "work"_s,
            // work:
            // «worker»
            // Runs the job.
            // invariant: retries >= 0
            // Never negative.
            // variable: progress = 0
            // Starts the clock.
            "work"_s + sml::on_entry<sml::_> / [] {},
            // do / invoke(job.py, http://example.com/worker)
            // Runs in a worker.
            // Kept until the job ends.
            "work"_s + sml::event<event::pause> / sml::defer,
            "work"_s + sml::event<event::resume> / sml::defer,
            // Timed out.
            "work"_s + sml::event<event::after_5s> / [] {} = "check"_s,
            "work"_s + sml::event<event::after_retryDelay> = "check"_s,
            "work"_s + sml::event<event::split> = sml::state<both>,
            "work"_s + sml::event<event::abort> = sml::X,
            "work"_s + sml::event<event::enter> = sml::state<outer>,
            sml::state<both> = sml::X,
            "sub"_s + sml::on_entry<sml::_> / [](::submachines& s) { s.sub.enterFsm(std::exchange(s.sub_entry, ChildFsm::Entry::initial)); },
            "sub"_s + sml::on_exit<sml::_> / [](::submachines& s) { s.sub.stopFsm(); },
            "sub"_s + sml::event<event::back> = "merge"_s,
            "sub"_s + sml::event<::internal::sub_finished> = sml::X,
            // Says goodbye.
            sml::state<outer> + sml::on_exit<sml::_> / [] {},
            sml::state<outer> = sml::X,
            "work"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            sml::state<both> + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            "sub"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            sml::state<outer> + sml::event<::internal::stop> = sml::state<::internal::stopped>
        );
    }
};

}  // namespace

struct UmlFsm::Machine {
    // Hands what the machine of "sub" reports to this one.
    struct SubListener : ChildFsmListener {
        explicit SubListener(UmlFsm& fsm) : fsm{fsm} {}
        void onFinished() override {
            if (fsm.machine_->process(internal::sub_finished{})) {
                fsm.report();
            }
        }
        UmlFsm& fsm;
    };

    Machine(UmlFsm& fsm, UmlFsmActions& actions, ChildFsm& sub)
        : machines{.sub = sub},
          sub_listener{fsm},
          sm{actions, machines} {
        sub.stopFsm();
        sub.setListener(&sub_listener);
    }

    ~Machine() {
        machines.sub.setListener(nullptr);
    }

    // Processes an event, or queues it while processing another, since a
    // submachine may report while this machine enters it. Returns whether it
    // processed the event.
    template <class Event>
    bool process(const Event& event) {
        if (busy) {
            queue.push_back([this, event] { sm.process_event(event); });
            return false;
        }
        busy = true;
        sm.process_event(event);
        while (!queue.empty()) {
            auto next = std::move(queue.front());
            queue.pop_front();
            next();
        }
        busy = false;
        return true;
    }

    ::submachines machines;
    SubListener sub_listener;
    sml::sm<machine, sml::defer_queue<std::deque>> sm;
    bool busy = false;
    std::deque<std::function<void()>> queue;
};

UmlFsm::UmlFsm(UmlFsmActions& actions, ChildFsm& sub)
    : actions_{actions},
      sub_{sub},
      machine_{std::make_unique<Machine>(*this, actions, sub)} {}

UmlFsm::~UmlFsm() = default;

void UmlFsm::enterFsm(Entry entry) {
    stopFsm();
    switch (entry) {
    case Entry::initial:
        if (machine_->process(internal::enter{})) {
            report();
        }
        break;
    }
}

void UmlFsm::stopFsm() {
    machine_->sm.process_event(internal::stop{});
    machine_.reset();
    machine_ = std::make_unique<Machine>(*this, actions_, sub_);
}

void UmlFsm::setListener(UmlFsmListener* listener) {
    listener_ = listener;
}

void UmlFsm::report() {
    if (listener_ == nullptr) {
        return;
    }
    if (machine_->sm.is(sml::X)) {
        stopFsm();
        listener_->onFinished();
    }
}

void UmlFsm::pause() {
    if (machine_->process(event::pause{})) {
        report();
    }
}

void UmlFsm::resume() {
    if (machine_->process(event::resume{})) {
        report();
    }
}

void UmlFsm::after_5s() {
    if (machine_->process(event::after_5s{})) {
        report();
    }
}

void UmlFsm::after_retryDelay() {
    if (machine_->process(event::after_retryDelay{})) {
        report();
    }
}

void UmlFsm::split() {
    if (machine_->process(event::split{})) {
        report();
    }
}

void UmlFsm::abort() {
    if (machine_->process(event::abort{})) {
        report();
    }
}

void UmlFsm::enter() {
    if (machine_->process(event::enter{})) {
        report();
    }
}

void UmlFsm::l() {
    if (machine_->process(event::l{})) {
        report();
    }
}

void UmlFsm::r() {
    if (machine_->process(event::r{})) {
        report();
    }
}

void UmlFsm::back() {
    if (machine_->process(event::back{})) {
        report();
    }
}

void UmlFsm::leave() {
    if (machine_->process(event::leave{})) {
        report();
    }
}

void UmlFsm::again() {
    if (machine_->process(event::again{})) {
        report();
    }
}

void UmlFsm::note() {
    if (machine_->process(event::note{})) {
        report();
    }
}
