// Generated by fsm from the state machine "uml". Do not edit.
#pragma once

#include "UmlFsmActions.h"
#include "UmlFsmEvents.h"

#include <memory>

// The state machine "uml".
//
// Every UML concept the model holds,
// in one document.
class UmlFsm : public UmlFsmEvents {
public:
    explicit UmlFsm(UmlFsmActions& actions);
    ~UmlFsm() override;

    UmlFsm(const UmlFsm&) = delete;
    UmlFsm& operator=(const UmlFsm&) = delete;

    void pause() override;
    void resume() override;
    void after_5s() override;
    void after_retryDelay() override;
    void split() override;
    void abort() override;
    void enter() override;
    void l() override;
    void r() override;
    void back() override;
    void leave() override;
    void again() override;
    void note() override;

private:
    struct Machine;
    std::unique_ptr<Machine> machine_;
};
