// Generated by fsm from the state machine "uml". Do not edit.
#pragma once

#include "FsmTimers.h"
#include "UmlFsmActions.h"
#include "UmlFsmEvents.h"

#include <memory>

class ChildFsm;

// What the state machine "uml" tells when it ends, as a submachine does.
class UmlFsmListener {
public:
    virtual ~UmlFsmListener() = default;

    // It reached its final state.
    virtual void onFinished() {}
    // It reached a terminate state.
    virtual void onTerminated() {}
};

// The state machine "uml".
//
// uml.scxml without what Boost.SML cannot run:
// do activities, local transitions and exit points of a state.
class UmlFsm : public UmlFsmEvents {
public:
    // Where enterFsm starts the machine: its initial state.
    enum class Entry { initial };

    // The machines the submachine states run, one each:
    // sub runs "child" in the state "sub".
    // timers runs the timers of the time triggers.
    explicit UmlFsm(UmlFsmActions& actions, FsmTimers& timers, ChildFsm& sub);
    ~UmlFsm() override;

    UmlFsm(const UmlFsm&) = delete;
    UmlFsm& operator=(const UmlFsm&) = delete;

    // Starts the machine, again if it runs, in its initial state.
    void enterFsm(Entry entry = Entry::initial);
    // Stops the machine: it leaves its states, running their exit behaviours, and
    // ignores every event until entered again.
    void stopFsm();
    // Ends the machine at once, as a terminate state does: no exit behaviour runs,
    // and it ignores every event until entered again.
    void terminateFsm();
    // Tells listener when the machine ends; nullptr tells no one.
    void setListener(UmlFsmListener* listener);

    void pause() override;
    void resume() override;
    void split() override;
    void abort() override;
    void enter() override;
    void l() override;
    void r() override;
    void back() override;
    void leave() override;
    void note() override;

private:
    void report();
    // Processes the event of a timer that fired.
    void fireTimer(int timer);

    struct Machine;
    UmlFsmActions& actions_;
    FsmTimers& timers_;
    ChildFsm& sub_;
    UmlFsmListener* listener_ = nullptr;
    std::unique_ptr<Machine> machine_;
};
