// Generated by fsm from the state machine "uml". Do not edit.
#include "UmlFsm.h"

#include <boost/sml.hpp>
#include <deque>

namespace {

namespace sml = boost::sml;

namespace event {
struct pause {};
struct resume {};
struct after_5s {};
struct after_retryDelay {};
struct split {};
struct abort {};
struct enter {};
struct l {};
struct r {};
struct back {};
struct leave {};
struct again {};
struct note {};
}  // namespace event

// The orthogonal state "both".
struct both {
    auto operator()() const {
        using namespace sml::literals;
        return sml::make_transition_table(
            *"left"_s + sml::event<event::l> = sml::X,
            *"right"_s + sml::event<event::r> = sml::X
        );
    }
};

// The composite state "outer".
struct outer {
    auto operator()() const {
        using namespace sml::literals;
        return sml::make_transition_table(
            *"outer.initial"_s / [] {} = "inner"_s,
            "inner"_s + sml::event<event::again> = "inner"_s,
            // Not drawn.
            "inner"_s + sml::event<event::note> / [] {}
        );
    }
};

struct machine {
    auto operator()() const {
        using namespace sml::literals;
        return sml::make_transition_table(
            // "check"_s [retries > 3] = sml::X
            // "check"_s [retries <= 3] = "work"_s
            *"check"_s + sml::on_entry<sml::_> / [] {},
            "merge"_s = "work"_s,
            // work:
            // «worker»
            // Runs the job.
            // invariant: retries >= 0
            // Never negative.
            // variable: progress = 0
            // Starts the clock.
            "work"_s + sml::on_entry<sml::_> / [] {},
            // do / invoke(job.py, http://example.com/worker)
            // Runs in a worker.
            // Kept until the job ends.
            "work"_s + sml::event<event::pause> / sml::defer,
            "work"_s + sml::event<event::resume> / sml::defer,
            // Timed out.
            "work"_s + sml::event<event::after_5s> / [] {} = "check"_s,
            "work"_s + sml::event<event::after_retryDelay> = "check"_s,
            "work"_s + sml::event<event::split> = sml::state<both>,
            "work"_s + sml::event<event::abort> = sml::X,
            "work"_s + sml::event<event::enter> = sml::state<outer>,
            sml::state<both> = sml::X,
            "sub"_s + sml::event<event::back> = "merge"_s,
            "sub"_s = sml::X,
            // Says goodbye.
            sml::state<outer> + sml::on_exit<sml::_> / [] {},
            sml::state<outer> = sml::X
        );
    }
};

}  // namespace

struct UmlFsm::Machine {
    explicit Machine(UmlFsmActions& actions) : sm{actions} {}
    sml::sm<machine, sml::defer_queue<std::deque>> sm;
};

UmlFsm::UmlFsm(UmlFsmActions& actions) : machine_{std::make_unique<Machine>(actions)} {}

UmlFsm::~UmlFsm() = default;

void UmlFsm::pause() { machine_->sm.process_event(event::pause{}); }
void UmlFsm::resume() { machine_->sm.process_event(event::resume{}); }
void UmlFsm::after_5s() { machine_->sm.process_event(event::after_5s{}); }
void UmlFsm::after_retryDelay() { machine_->sm.process_event(event::after_retryDelay{}); }
void UmlFsm::split() { machine_->sm.process_event(event::split{}); }
void UmlFsm::abort() { machine_->sm.process_event(event::abort{}); }
void UmlFsm::enter() { machine_->sm.process_event(event::enter{}); }
void UmlFsm::l() { machine_->sm.process_event(event::l{}); }
void UmlFsm::r() { machine_->sm.process_event(event::r{}); }
void UmlFsm::back() { machine_->sm.process_event(event::back{}); }
void UmlFsm::leave() { machine_->sm.process_event(event::leave{}); }
void UmlFsm::again() { machine_->sm.process_event(event::again{}); }
void UmlFsm::note() { machine_->sm.process_event(event::note{}); }
