// Generated by fsm from the state machine "uml". Do not edit.
#pragma once

#include <chrono>

// The guards and actions the state machine "uml" calls.
// Implement them and pass the implementation to UmlFsm's constructor.
//
// The machine's variables, which the implementation holds:
//   retries = 0
//   config = src(config.json)
class UmlFsmActions {
public:
    virtual ~UmlFsmActions() = default;

    // Delays, read when a timer starts
    virtual std::chrono::milliseconds retryDelay() const = 0;
};
