// Generated by fsm from the state machine "uml". Do not edit.
#pragma once

// The events the state machine "uml" reacts to.
class UmlFsmEvents {
public:
    virtual ~UmlFsmEvents() = default;

    virtual void pause() = 0;
    virtual void resume() = 0;
    virtual void after_5s() = 0;
    virtual void after_retryDelay() = 0;
    virtual void split() = 0;
    virtual void abort() = 0;
    virtual void enter() = 0;
    virtual void l() = 0;
    virtual void r() = 0;
    virtual void back() = 0;
    virtual void leave() = 0;
    virtual void again() = 0;
    virtual void note() = 0;
};
