// Generated by fsm from the state machine "uml". Do not edit.
#include "UmlFsm.h"
#include "ChildFsm.h"

#include <boost/sml.hpp>
#include <deque>
#include <functional>
#include <memory>
#include <utility>

namespace {

namespace sml = boost::sml;

namespace event {
struct pause {};
struct resume {};
struct split {};
struct abort {};
struct enter {};
struct l {};
struct r {};
struct back {};
struct leave {};
struct again {};
struct note {};
}  // namespace event

// The events the machine sends itself, and the state it waits in until entered.
namespace internal {
struct stopped {};
struct enter {};
struct stop {};
struct work_after_5s {};
struct work_after_retryDelay {};
struct terminated {};
struct sub_finished {};
}  // namespace internal

// Whether the machine reached a terminate state, its own or one of a machine it
// runs: it ends once the current event is done.
struct status {
    bool terminated = false;
};

// The timers of the time triggers. A state starts its timers when it is entered
// and cancels them when it is left. A timer that fires after that, or after the
// machine was rebuilt, does nothing.
struct timers {
    enum id { work_after_5s, work_after_retryDelay };

    timers(FsmTimers& service, std::function<void(id)> fire) : service{service}, fire{std::move(fire)} {}
    timers(const timers&) = delete;
    timers& operator=(const timers&) = delete;
    ~timers() {
        for (auto& slot : slots) {
            if (slot.running) {
                service.cancelTimer(slot.handle);
            }
        }
    }

    void start(id timer, std::chrono::milliseconds delay) {
        cancel(timer);
        auto& slot = slots[timer];
        slot.running = std::make_shared<bool>();
        slot.handle = service.startTimer(delay, [this, timer, running = std::weak_ptr<bool>{slot.running}] {
            if (!running.expired()) {
                slots[timer].running.reset();
                fire(timer);
            }
        });
    }

    void cancel(id timer) {
        auto& slot = slots[timer];
        if (slot.running) {
            slot.running.reset();
            service.cancelTimer(slot.handle);
        }
    }

    FsmTimers& service;
    std::function<void(id)> fire;
    // running is set while the timer runs; its callback watches it.
    struct {
        FsmTimers::Id handle = 0;
        std::shared_ptr<bool> running;
    } slots[2];
};

// The machines the submachine states run, and the entry point each starts at next.
struct submachines {
    ChildFsm& sub;
    ChildFsm::Entry sub_entry = ChildFsm::Entry::initial;
};

// The orthogonal state "both".
struct both {
    auto operator()() const {
        using namespace sml::literals;
        return sml::make_transition_table(
            *"left"_s + sml::event<event::l> = sml::X,
            *"right"_s + sml::event<event::r> = sml::X
        );
    }
};

// The composite state "outer".
struct outer {
    auto operator()() const {
        using namespace sml::literals;
        return sml::make_transition_table(
            *"outer.initial"_s / [] {} = "inner"_s,
            "inner"_s + sml::event<event::again> = "inner"_s,
            // Not drawn.
            "inner"_s + sml::event<event::note> / [] {}
        );
    }
};

struct machine {
    auto operator()() const {
        using namespace sml::literals;
        using sml::operator!, sml::operator&&, sml::operator||, sml::operator,;
        return sml::make_transition_table(
            *sml::state<::internal::stopped> + sml::event<::internal::enter> = "check"_s,
            // "check"_s [retries > 3] = sml::X
            // "check"_s [retries <= 3] = "work"_s
            "merge"_s = "work"_s,
            // work:
            // «worker»
            // Runs the job.
            // invariant: retries >= 0
            // Never negative.
            // variable: progress = 0
            // Starts the clock.
            "work"_s + sml::on_entry<sml::_> / ([](::timers& t) { t.start(::timers::work_after_5s, std::chrono::seconds{5}); }, [](::timers& t, const UmlFsmActions& actions) { t.start(::timers::work_after_retryDelay, actions.retryDelay()); }),
            "work"_s + sml::on_exit<sml::_> / ([](::timers& t) { t.cancel(::timers::work_after_5s); }, [](::timers& t) { t.cancel(::timers::work_after_retryDelay); }),
            // do / invoke(job.py, http://example.com/worker)
            // Runs in a worker.
            // Kept until the job ends.
            "work"_s + sml::event<event::pause> / sml::defer,
            "work"_s + sml::event<event::resume> / sml::defer,
            // Timed out.
            "work"_s + sml::event<::internal::work_after_5s> / [] {} = "check"_s,
            "work"_s + sml::event<::internal::work_after_retryDelay> = "check"_s,
            "work"_s + sml::event<event::split> = sml::state<both>,
            "work"_s + sml::event<event::abort> = sml::state<::internal::terminated>,
            "work"_s + sml::event<event::enter> = sml::state<outer>,
            sml::state<both> = sml::X,
            "sub"_s + sml::on_entry<sml::_> / [](::submachines& s) { s.sub.enterFsm(std::exchange(s.sub_entry, ChildFsm::Entry::initial)); },
            "sub"_s + sml::on_exit<sml::_> / [](::submachines& s) { s.sub.stopFsm(); },
            "sub"_s + sml::event<event::back> = "merge"_s,
            "sub"_s + sml::event<::internal::sub_finished> = sml::X,
            // Says goodbye.
            sml::state<outer> + sml::on_exit<sml::_> / [] {},
            sml::state<outer> = sml::X,
            sml::state<::internal::terminated> + sml::on_entry<sml::_> / [](::status& s) { s.terminated = true; },
            "work"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            sml::state<both> + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            "sub"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            sml::state<outer> + sml::event<::internal::stop> = sml::state<::internal::stopped>
        );
    }
};

}  // namespace

struct UmlFsm::Machine {
    // Hands what the machine of "sub" reports to this one.
    struct SubListener : ChildFsmListener {
        explicit SubListener(UmlFsm& fsm) : fsm{fsm} {}
        void onTerminated() override {
            fsm.machine_->status.terminated = true;
            if (!fsm.machine_->busy) {
                fsm.report();
            }
        }
        void onFinished() override {
            if (fsm.machine_->process(internal::sub_finished{})) {
                fsm.report();
            }
        }
        UmlFsm& fsm;
    };

    Machine(UmlFsm& fsm, UmlFsmActions& actions, FsmTimers& service, ChildFsm& sub)
        : machines{.sub = sub},
          sub_listener{fsm},
          timers{service, [fsm = &fsm](::timers::id timer) { fsm->fireTimer(timer); }},
          sm{actions, machines, status, timers} {
        sub.terminateFsm();
        sub.setListener(&sub_listener);
    }

    ~Machine() {
        machines.sub.setListener(nullptr);
    }

    // Processes an event, or queues it while processing another, since a
    // submachine may report while this machine enters it. Returns whether it
    // processed the event.
    template <class Event>
    bool process(const Event& event) {
        if (busy) {
            queue.push_back([this, event] { sm.process_event(event); });
            return false;
        }
        busy = true;
        sm.process_event(event);
        while (!queue.empty() && !status.terminated) {
            auto next = std::move(queue.front());
            queue.pop_front();
            next();
        }
        busy = false;
        return true;
    }

    ::submachines machines;
    SubListener sub_listener;
    ::status status;
    ::timers timers;
    sml::sm<machine, sml::defer_queue<std::deque>> sm;
    bool busy = false;
    std::deque<std::function<void()>> queue;
};

UmlFsm::UmlFsm(UmlFsmActions& actions, FsmTimers& timers, ChildFsm& sub)
    : actions_{actions},
      timers_{timers},
      sub_{sub},
      machine_{std::make_unique<Machine>(*this, actions, timers, sub)} {}

UmlFsm::~UmlFsm() = default;

void UmlFsm::enterFsm(Entry entry) {
    stopFsm();
    switch (entry) {
    case Entry::initial:
        if (machine_->process(internal::enter{})) {
            report();
        }
        break;
    }
}

void UmlFsm::stopFsm() {
    machine_->sm.process_event(internal::stop{});
    terminateFsm();
}

void UmlFsm::terminateFsm() {
    machine_.reset();
    machine_ = std::make_unique<Machine>(*this, actions_, timers_, sub_);
}

void UmlFsm::setListener(UmlFsmListener* listener) {
    listener_ = listener;
}

void UmlFsm::report() {
    if (machine_->status.terminated) {
        terminateFsm();
        if (listener_ != nullptr) {
            listener_->onTerminated();
        }
        return;
    }
    if (listener_ == nullptr) {
        return;
    }
    if (machine_->sm.is(sml::X)) {
        stopFsm();
        listener_->onFinished();
    }
}

void UmlFsm::fireTimer(int timer) {
    switch (timer) {
    case ::timers::work_after_5s:
        if (machine_->process(internal::work_after_5s{})) {
            report();
        }
        break;
    case ::timers::work_after_retryDelay:
        if (machine_->process(internal::work_after_retryDelay{})) {
            report();
        }
        break;
    }
}

void UmlFsm::pause() {
    if (machine_->process(event::pause{})) {
        report();
    }
}

void UmlFsm::resume() {
    if (machine_->process(event::resume{})) {
        report();
    }
}

void UmlFsm::split() {
    if (machine_->process(event::split{})) {
        report();
    }
}

void UmlFsm::abort() {
    if (machine_->process(event::abort{})) {
        report();
    }
}

void UmlFsm::enter() {
    if (machine_->process(event::enter{})) {
        report();
    }
}

void UmlFsm::l() {
    if (machine_->process(event::l{})) {
        report();
    }
}

void UmlFsm::r() {
    if (machine_->process(event::r{})) {
        report();
    }
}

void UmlFsm::back() {
    if (machine_->process(event::back{})) {
        report();
    }
}

void UmlFsm::leave() {
    if (machine_->process(event::leave{})) {
        report();
    }
}

void UmlFsm::again() {
    if (machine_->process(event::again{})) {
        report();
    }
}

void UmlFsm::note() {
    if (machine_->process(event::note{})) {
        report();
    }
}
