// Generated by fsm from the state machine "kiosk". Do not edit.
#pragma once

#include "KioskFsmActions.h"
#include "KioskFsmEvents.h"

#include <memory>

// The state machine "kiosk".
//
// A self-service kiosk:
// browse, pay, take the receipt.
class KioskFsm : public KioskFsmEvents {
public:
    explicit KioskFsm(KioskFsmActions& actions);
    ~KioskFsm() override;

    KioskFsm(const KioskFsm&) = delete;
    KioskFsm& operator=(const KioskFsm&) = delete;

    void touch() override;
    void abandon() override;
    void after_90s() override;
    void resume() override;
    void back() override;
    void add() override;
    void remove() override;
    void checkout() override;
    void approved() override;
    void declined() override;
    void cancel() override;
    void after_authTimeout() override;
    void card() override;
    void ack() override;

private:
    struct Machine;
    std::unique_ptr<Machine> machine_;
};
