// Generated by fsm from the state machine "kiosk". Do not edit.
#include "KioskFsm.h"

#include <boost/sml.hpp>
#include <deque>
#include <functional>
#include <memory>
#include <utility>

namespace {

namespace sml = boost::sml;

namespace event {
struct touch {};
struct abandon {};
struct resume {};
struct back {};
struct add {};
struct remove {};
struct checkout {};
struct approved {};
struct declined {};
struct cancel {};
struct card {};
struct ack {};
}  // namespace event

// The events the machine sends itself, and the state it waits in until entered.
namespace internal {
struct stopped {};
struct enter {};
struct stop {};
struct ordering_after_90s {};
struct authorizing_after_authTimeout {};
}  // namespace internal

// The timers of the time triggers. A state starts its timers when it is entered
// and cancels them when it is left. A timer that fires after that, or after the
// machine was rebuilt, does nothing.
struct timers {
    enum id { ordering_after_90s, authorizing_after_authTimeout };

    timers(FsmTimers& service, std::function<void(id)> fire) : service{service}, fire{std::move(fire)} {}
    timers(const timers&) = delete;
    timers& operator=(const timers&) = delete;
    ~timers() {
        for (auto& slot : slots) {
            if (slot.running) {
                service.cancelTimer(slot.handle);
            }
        }
    }

    void start(id timer, std::chrono::milliseconds delay) {
        cancel(timer);
        auto& slot = slots[timer];
        slot.running = std::make_shared<bool>();
        slot.handle = service.startTimer(delay, [this, timer, running = std::weak_ptr<bool>{slot.running}] {
            if (!running.expired()) {
                slots[timer].running.reset();
                fire(timer);
            }
        });
    }

    void cancel(id timer) {
        auto& slot = slots[timer];
        if (slot.running) {
            slot.running.reset();
            service.cancelTimer(slot.handle);
        }
    }

    FsmTimers& service;
    std::function<void(id)> fire;
    // running is set while the timer runs; its callback watches it.
    struct {
        FsmTimers::Id handle = 0;
        std::shared_ptr<bool> running;
    } slots[2];
};

// The composite state "paying".
struct paying {
    auto operator()() const {
        using namespace sml::literals;
        const auto retries = [](const KioskFsmActions& actions) { return actions.retries(); };
        const auto warn = [](KioskFsmActions& actions) { actions.warn(); };
        return sml::make_transition_table(
            *"authorizing"_s + sml::on_entry<sml::_> / [](::timers& t, const KioskFsmActions& actions) { t.start(::timers::authorizing_after_authTimeout, actions.authTimeout()); },
            "authorizing"_s + sml::on_exit<sml::_> / [](::timers& t) { t.cancel(::timers::authorizing_after_authTimeout); },
            // do / spin
            // Until the bank answers.
            "authorizing"_s + sml::event<event::touch> / sml::defer,
            "authorizing"_s + sml::event<::internal::authorizing_after_authTimeout> [retries] / warn = "again"_s,
            "again"_s + sml::event<event::card> = "authorizing"_s
        );
    }
};

// The composite state "ordering".
struct ordering {
    auto operator()() const {
        using namespace sml::literals;
        using sml::operator!, sml::operator&&, sml::operator||, sml::operator,;
        const auto inStock = [](const KioskFsmActions& actions) { return actions.inStock(); };
        const auto card = [](const KioskFsmActions& actions) { return actions.card(); };
        const auto cash = [](const KioskFsmActions& actions) { return actions.cash(); };
        const auto basket = [](const KioskFsmActions& actions) { return actions.basket(); };
        const auto retries = [](const KioskFsmActions& actions) { return actions.retries(); };
        const auto addLine = [](KioskFsmActions& actions) { actions.addLine(); };
        const auto dropLine = [](KioskFsmActions& actions) { actions.dropLine(); };
        const auto lockBasket = [](KioskFsmActions& actions) { actions.lockBasket(); };
        const auto warn = [](KioskFsmActions& actions) { actions.warn(); };
        return sml::make_transition_table(
            "browsing"_s(sml::H) + sml::event<event::add> [inStock && (card || cash)] / addLine,
            "browsing"_s + sml::event<event::remove> / dropLine = "browsing"_s,
            "browsing"_s + sml::event<event::checkout> [basket] = sml::state<paying>,
            // paying:
            // The basket is locked from here on.
            // invariant: basket and not (card and cash)
            sml::state<paying> + sml::on_entry<sml::_> / lockBasket,
            sml::state<paying> + sml::event<event::declined> [retries] / warn = sml::state<paying>,
            sml::state<paying> + sml::event<event::declined> [!retries] = "browsing"_s,
            sml::state<paying> + sml::event<event::cancel> = "browsing"_s
        );
    }
};

struct machine {
    auto operator()() const {
        using namespace sml::literals;
        using sml::operator!, sml::operator&&, sml::operator||, sml::operator,;
        const auto boot = [](KioskFsmActions& actions) { actions.boot(); };
        const auto dim = [](KioskFsmActions& actions) { actions.dim(); };
        const auto wake = [](KioskFsmActions& actions) { actions.wake(); };
        const auto newBasket = [](KioskFsmActions& actions) { actions.newBasket(); };
        const auto clearBasket = [](KioskFsmActions& actions) { actions.clearBasket(); };
        const auto unlock = [](KioskFsmActions& actions) { actions.unlock(); };
        const auto receipt = [](KioskFsmActions& actions) { actions.receipt(); };
        const auto print = [](KioskFsmActions& actions) { actions.print(); };
        return sml::make_transition_table(
            *sml::state<::internal::stopped> + sml::event<::internal::enter> / boot = "idle"_s,
            "idle"_s + sml::on_entry<sml::_> / dim,
            "idle"_s + sml::event<event::touch> / wake = sml::state<ordering>,
            sml::state<ordering> + sml::on_entry<sml::_> / (newBasket, [](::timers& t) { t.start(::timers::ordering_after_90s, std::chrono::seconds{90}); }),
            sml::state<ordering> + sml::on_exit<sml::_> / ([](::timers& t) { t.cancel(::timers::ordering_after_90s); }, clearBasket, unlock),
            sml::state<ordering> + sml::event<event::abandon> = "idle"_s,
            // Nobody touched the screen.
            sml::state<ordering> + sml::event<::internal::ordering_after_90s> = "idle"_s,
            sml::state<ordering> + sml::event<event::resume> = sml::state<ordering>,
            sml::state<ordering> + sml::event<event::back> = sml::state<ordering>,
            sml::state<ordering> + sml::event<event::approved> / receipt = "done"_s,
            "done"_s + sml::on_entry<sml::_> / print,
            "done"_s + sml::event<event::ack> = sml::X,
            "idle"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            sml::state<ordering> + sml::event<::internal::stop> = sml::state<::internal::stopped>,
            "done"_s + sml::event<::internal::stop> = sml::state<::internal::stopped>
        );
    }
};

}  // namespace

struct KioskFsm::Machine {
    Machine(KioskFsm& fsm, KioskFsmActions& actions, FsmTimers& service)
        : timers{service, [fsm = &fsm](::timers::id timer) { fsm->fireTimer(timer); }},
          sm{actions, timers} {}
    ::timers timers;
    sml::sm<machine, sml::defer_queue<std::deque>> sm;
};

KioskFsm::KioskFsm(KioskFsmActions& actions, FsmTimers& timers)
    : actions_{actions},
      timers_{timers},
      machine_{std::make_unique<Machine>(*this, actions, timers)} {}

KioskFsm::~KioskFsm() = default;

void KioskFsm::enterFsm(Entry entry) {
    stopFsm();
    switch (entry) {
    case Entry::initial:
        machine_->sm.process_event(internal::enter{});
        report();
        break;
    }
}

void KioskFsm::stopFsm() {
    machine_->sm.process_event(internal::stop{});
    terminateFsm();
}

void KioskFsm::terminateFsm() {
    machine_.reset();
    machine_ = std::make_unique<Machine>(*this, actions_, timers_);
}

void KioskFsm::setListener(KioskFsmListener* listener) {
    listener_ = listener;
}

void KioskFsm::report() {
    if (listener_ == nullptr) {
        return;
    }
    if (machine_->sm.is(sml::X)) {
        stopFsm();
        listener_->onFinished();
    }
}

void KioskFsm::fireTimer(int timer) {
    switch (timer) {
    case ::timers::ordering_after_90s:
        machine_->sm.process_event(internal::ordering_after_90s{});
        report();
        break;
    case ::timers::authorizing_after_authTimeout:
        machine_->sm.process_event(internal::authorizing_after_authTimeout{});
        report();
        break;
    }
}

void KioskFsm::touch() {
    machine_->sm.process_event(event::touch{});
    report();
}

void KioskFsm::abandon() {
    machine_->sm.process_event(event::abandon{});
    report();
}

void KioskFsm::resume() {
    machine_->sm.process_event(event::resume{});
    report();
}

void KioskFsm::back() {
    machine_->sm.process_event(event::back{});
    report();
}

void KioskFsm::add() {
    machine_->sm.process_event(event::add{});
    report();
}

void KioskFsm::remove() {
    machine_->sm.process_event(event::remove{});
    report();
}

void KioskFsm::checkout() {
    machine_->sm.process_event(event::checkout{});
    report();
}

void KioskFsm::approved() {
    machine_->sm.process_event(event::approved{});
    report();
}

void KioskFsm::declined() {
    machine_->sm.process_event(event::declined{});
    report();
}

void KioskFsm::cancel() {
    machine_->sm.process_event(event::cancel{});
    report();
}

void KioskFsm::card() {
    machine_->sm.process_event(event::card{});
    report();
}

void KioskFsm::ack() {
    machine_->sm.process_event(event::ack{});
    report();
}
