// Generated by fsm from the state machine "kiosk". Do not edit.
#pragma once

#include "FsmTimers.h"
#include "KioskFsmActions.h"
#include "KioskFsmEvents.h"

#include <memory>

// What the state machine "kiosk" tells when it ends, as a submachine does, and when
// an invariant does not hold.
class KioskFsmListener {
public:
    virtual ~KioskFsmListener() = default;

    // It reached its final state.
    virtual void onFinished() {}
    // It reached a terminate state.
    virtual void onTerminated() {}
    // The invariant of the active state named state does not hold, after it was
    // entered or after an event.
    virtual void onInvariantViolated(const char* /*state*/) {}
};

// The state machine "kiosk".
//
// A self-service kiosk:
// browse, pay, take the receipt.
class KioskFsm : public KioskFsmEvents {
public:
    // Where enterFsm starts the machine: its initial state.
    enum class Entry { initial };

    // timers runs the timers of the time triggers.
    explicit KioskFsm(KioskFsmActions& actions, FsmTimers& timers);
    ~KioskFsm() override;

    KioskFsm(const KioskFsm&) = delete;
    KioskFsm& operator=(const KioskFsm&) = delete;

    // Starts the machine, again if it runs, in its initial state.
    void enterFsm(Entry entry = Entry::initial);
    // Stops the machine: it leaves its states, running their exit behaviours, and
    // ignores every event until entered again.
    void stopFsm();
    // Ends the machine at once, as a terminate state does: no exit behaviour runs,
    // and it ignores every event until entered again.
    void terminateFsm();
    // Tells listener when the machine ends; nullptr tells no one.
    void setListener(KioskFsmListener* listener);

    void touch() override;
    void abandon() override;
    void resume() override;
    void add() override;
    void remove() override;
    void checkout() override;
    void declined() override;
    void approved() override;
    void card() override;
    void ack() override;

private:
    void report();
    // Processes the event of a timer that fired.
    void fireTimer(int timer);
    // Tells the listener about each active state whose invariant does not hold.
    void checkInvariants();

    struct Machine;
    KioskFsmActions& actions_;
    FsmTimers& timers_;
    KioskFsmListener* listener_ = nullptr;
    std::unique_ptr<Machine> machine_;
};
