// Generated by fsm from the state machine "kiosk". Do not edit.
#pragma once

#include <chrono>

// The guards and actions the state machine "kiosk" calls.
// Implement them and pass the implementation to KioskFsm's constructor.
class KioskFsmActions {
public:
    virtual ~KioskFsmActions() = default;

    // Guards
    virtual bool basket() const = 0;
    virtual bool card() const = 0;
    virtual bool cash() const = 0;
    virtual bool inStock() const = 0;
    virtual bool retries() const = 0;

    // Actions
    virtual void addLine() = 0;
    virtual void boot() = 0;
    virtual void clearBasket() = 0;
    virtual void dim() = 0;
    virtual void dropLine() = 0;
    virtual void lockBasket() = 0;
    virtual void newBasket() = 0;
    virtual void print() = 0;
    virtual void receipt() = 0;
    virtual void unlock() = 0;
    virtual void wake() = 0;
    virtual void warn() = 0;

    // Invariants, checked while their state is active
    virtual bool invariantBasket() const = 0;
    virtual bool invariantCard() const = 0;
    virtual bool invariantCash() const = 0;

    // Delays, read when a timer starts
    virtual std::chrono::milliseconds authTimeout() const = 0;
};
