// Generated by fsm from the state machine "kiosk". Do not edit.
#include "KioskFsm.h"

#include <boost/sml.hpp>
#include <deque>

namespace {

namespace sml = boost::sml;

namespace event {
struct touch {};
struct abandon {};
struct after_90s {};
struct resume {};
struct back {};
struct add {};
struct remove {};
struct checkout {};
struct approved {};
struct declined {};
struct cancel {};
struct after_authTimeout {};
struct card {};
struct ack {};
}  // namespace event

// The composite state "paying".
struct paying {
    auto operator()() const {
        using namespace sml::literals;
        const auto retries = [](const KioskFsmActions& actions) { return actions.retries(); };
        const auto warn = [](KioskFsmActions& actions) { actions.warn(); };
        return sml::make_transition_table(
            // do / spin
            // Until the bank answers.
            *"authorizing"_s + sml::event<event::touch> / sml::defer,
            "authorizing"_s + sml::event<event::after_authTimeout> [retries] / warn = "again"_s,
            "again"_s + sml::event<event::card> = "authorizing"_s
        );
    }
};

// The composite state "ordering".
struct ordering {
    auto operator()() const {
        using namespace sml::literals;
        using sml::operator!, sml::operator&&, sml::operator||, sml::operator,;
        const auto inStock = [](const KioskFsmActions& actions) { return actions.inStock(); };
        const auto card = [](const KioskFsmActions& actions) { return actions.card(); };
        const auto cash = [](const KioskFsmActions& actions) { return actions.cash(); };
        const auto basket = [](const KioskFsmActions& actions) { return actions.basket(); };
        const auto retries = [](const KioskFsmActions& actions) { return actions.retries(); };
        const auto addLine = [](KioskFsmActions& actions) { actions.addLine(); };
        const auto dropLine = [](KioskFsmActions& actions) { actions.dropLine(); };
        const auto lockBasket = [](KioskFsmActions& actions) { actions.lockBasket(); };
        const auto warn = [](KioskFsmActions& actions) { actions.warn(); };
        return sml::make_transition_table(
            "browsing"_s(sml::H) + sml::event<event::add> [inStock && (card || cash)] / addLine,
            "browsing"_s + sml::event<event::remove> / dropLine = "browsing"_s,
            "browsing"_s + sml::event<event::checkout> [basket] = sml::state<paying>,
            // paying:
            // The basket is locked from here on.
            // invariant: basket and not (card and cash)
            sml::state<paying> + sml::on_entry<sml::_> / lockBasket,
            sml::state<paying> + sml::event<event::declined> [retries] / warn = sml::state<paying>,
            sml::state<paying> + sml::event<event::declined> [!retries] = "browsing"_s,
            sml::state<paying> + sml::event<event::cancel> = "browsing"_s
        );
    }
};

struct machine {
    auto operator()() const {
        using namespace sml::literals;
        using sml::operator!, sml::operator&&, sml::operator||, sml::operator,;
        const auto boot = [](KioskFsmActions& actions) { actions.boot(); };
        const auto dim = [](KioskFsmActions& actions) { actions.dim(); };
        const auto wake = [](KioskFsmActions& actions) { actions.wake(); };
        const auto newBasket = [](KioskFsmActions& actions) { actions.newBasket(); };
        const auto clearBasket = [](KioskFsmActions& actions) { actions.clearBasket(); };
        const auto unlock = [](KioskFsmActions& actions) { actions.unlock(); };
        const auto receipt = [](KioskFsmActions& actions) { actions.receipt(); };
        const auto print = [](KioskFsmActions& actions) { actions.print(); };
        return sml::make_transition_table(
            *"initial"_s / boot = "idle"_s,
            "idle"_s + sml::on_entry<sml::_> / dim,
            "idle"_s + sml::event<event::touch> / wake = sml::state<ordering>,
            sml::state<ordering> + sml::on_entry<sml::_> / newBasket,
            sml::state<ordering> + sml::on_exit<sml::_> / (clearBasket, unlock),
            sml::state<ordering> + sml::event<event::abandon> = "idle"_s,
            // Nobody touched the screen.
            sml::state<ordering> + sml::event<event::after_90s> = "idle"_s,
            sml::state<ordering> + sml::event<event::resume> = sml::state<ordering>,
            sml::state<ordering> + sml::event<event::back> = sml::state<ordering>,
            sml::state<ordering> + sml::event<event::approved> / receipt = "done"_s,
            "done"_s + sml::on_entry<sml::_> / print,
            "done"_s + sml::event<event::ack> = sml::X
        );
    }
};

}  // namespace

struct KioskFsm::Machine {
    explicit Machine(KioskFsmActions& actions) : sm{actions} {}
    sml::sm<machine, sml::defer_queue<std::deque>> sm;
};

KioskFsm::KioskFsm(KioskFsmActions& actions) : machine_{std::make_unique<Machine>(actions)} {}

KioskFsm::~KioskFsm() = default;

void KioskFsm::touch() { machine_->sm.process_event(event::touch{}); }
void KioskFsm::abandon() { machine_->sm.process_event(event::abandon{}); }
void KioskFsm::after_90s() { machine_->sm.process_event(event::after_90s{}); }
void KioskFsm::resume() { machine_->sm.process_event(event::resume{}); }
void KioskFsm::back() { machine_->sm.process_event(event::back{}); }
void KioskFsm::add() { machine_->sm.process_event(event::add{}); }
void KioskFsm::remove() { machine_->sm.process_event(event::remove{}); }
void KioskFsm::checkout() { machine_->sm.process_event(event::checkout{}); }
void KioskFsm::approved() { machine_->sm.process_event(event::approved{}); }
void KioskFsm::declined() { machine_->sm.process_event(event::declined{}); }
void KioskFsm::cancel() { machine_->sm.process_event(event::cancel{}); }
void KioskFsm::after_authTimeout() { machine_->sm.process_event(event::after_authTimeout{}); }
void KioskFsm::card() { machine_->sm.process_event(event::card{}); }
void KioskFsm::ack() { machine_->sm.process_event(event::ack{}); }
